---
apiVersion: v1 
kind: Service
metadata:
  name: nginx service file
  labels:
    env: prod
spec:
  selector:
    env: prod
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000